application: red-bruin-387
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /images
  static_dir: images
  
- url: /javascripts
  static_dir: javascripts

- url: /(.*\.(gif|png|jpg|xml))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|xml))